title: KaptinBot wiki
description: Wiki for KaptinBot
markdown: kramdown
google_analytics: G-TQ37R5G1QM
permalink: /kaptinbot/commands/:title
theme: minima
paginate: 5
paginate_path: "commands/page:num"
excerpt_separator: <!--more-->
